services:
  - type: web
    name: autosite
    runtime: python
    buildCommand: bash ./build.sh
    startCommand: gunicorn autoservice.wsgi:application --log-file -
    healthCheckPath: /
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: autoservice.settings_production
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SITE_URL
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_DB_CONN_MAX_AGE
        value: "600"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: "1"
      - key: DJANGO_SECURE_HSTS_SECONDS
        value: "3600"
      - key: DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "1"
      - key: DJANGO_SECURE_HSTS_PRELOAD
        value: "0"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_REGION_NAME
        value: auto
      - key: AWS_S3_ENDPOINT_URL
        sync: false
      - key: AWS_S3_CUSTOM_DOMAIN
        sync: false
      - key: DJANGO_MEDIA_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
