# Generated by Django 6.0.3 on 2026-03-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.FileField(blank=True, upload_to='support/images/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_message',
            field=models.FileField(blank=True, upload_to='support/voice/%Y/%m/', verbose_name='Голосовое сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение'),
        ),
    ]
