# Generated by Django 6.0.3 on 2026-03-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCharacteristicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Группа характеристик')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Группа характеристик',
                'verbose_name_plural': 'Группы характеристик',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CarCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название характеристики')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('value_type', models.CharField(choices=[('int', 'Целое'), ('decimal', 'Дробное'), ('bool', 'Да/Нет'), ('text', 'Текст'), ('enum', 'Перечень')], default='text', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='Единицы измерения')),
                ('enum_options', models.TextField(blank=True, help_text='Пример: 4WD, AWD, FWD, RWD', verbose_name='Варианты (для ENUM, через запятую)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.carcharacteristicgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ('group__order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CarCharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='Значение (int)')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Значение (decimal)')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='Значение (bool)')),
                ('value_text', models.TextField(blank=True, verbose_name='Значение (text)')),
                ('value_enum', models.CharField(blank=True, max_length=200, verbose_name='Значение (enum)')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_values', to='catalog.car', verbose_name='Машина')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.carcharacteristic', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
                'constraints': [models.UniqueConstraint(fields=('car', 'characteristic'), name='unique_car_characteristic_value')],
            },
        ),
    ]
