# Generated by Codex on 2026-03-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_carcharacteristicgroup_carcharacteristic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.FileField(upload_to="cars/%Y/%m/", verbose_name="Изображение")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("alt_text", models.CharField(blank=True, max_length=200, verbose_name="Альтернативный текст")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.car",
                        verbose_name="Машина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение машины",
                "verbose_name_plural": "Изображения машин",
                "ordering": ["order"],
            },
        ),
    ]
