# Generated by Django 6.0.3 on 2026-03-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveBigIntegerField(default=0, verbose_name='Посещения сайта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Метрика сайта',
                'verbose_name_plural': 'Метрики сайта',
            },
        ),
    ]
